version: '3.8'

services:
  redis-watcher:
    build: .
    container_name: redis-watcher
    ports:
      - '5000:5000'
    volumes:
      - ./config:/app/config
    environment:
      - REDIS_CONFIG_PATH=/app/config/redis-config.json
